product/urls.py
from unicodedata import name
from django.urls import path
from .views import *
from . import views




app_name = 'product'
urlpatterns =[
    path('',views.home, name='home'),
    path('our_team/',views.team, name='our_team'),
    path('property/',views.property, name='property'),
    path('management/',views.management, name='management'),
    path('marketing/',views.marketing, name='marketing'),
    path('testimonial/',views.testimonial, name='testimonial'),
    path('contactus/',views.contact_us, name='contactus'),
    path('property_search/' ,views.availableProperty,name='property_search'),

    
   path('image_gallery/<int:id>/', views.imageGallery, name='image_gallery'),

    path('feature_gallery/<int:id>/', views.featuredImageGallery, name='feature_gallery'),

    path('services/',views.services,name='services'),
   path('image_slides/<int:id>/', views.imageSlides, name='image_slides'),
    path('add_item/<int:pk>', views.add_to_cart, name='add_item'),
    path('search_p/' ,views.propertySearches,name="search_p"),
    
    path('all_property/' ,views.allItems,name="all_property"),
    
]

realestate/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('product.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL ,document_root =settings.MEDIA_ROOT)

templates/allProperties.html
{% extends 'first.html' %}
{% load static %}
{% block title %}PropertyInformation{% endblock %}
{% block content %}



<style>

   

.flex-container {
  display: flex;
  flex-wrap: wrap;
  margin-top: 25px;
}

.flex-item-left {
  flex: 50%;
}

.flex-item-right {
  flex: 50%;
}
.card-image{
    width: 300px;
    height: 280px;
    margin-left: 20px;
}
.card-image img{
    width: 100%;
    height: 100%;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    border: 2px solid #7bdcb5;
}
.property-information{
    margin-left: 20px;
}
.property-address h2{
    font-size: 20px;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    font-weight: 400;
  
    color: #0076AD;
    margin-left: 10px;
}
.property-information h3{
    font-size: 18px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #333;

}
.property-information span{
    color: green;
}
.right{
    margin-left: 50px;
}
.search-result{
    margin-left: 30px;
}
.search-section .description{
    font-size: 15px;
    color: #333;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    margin-top: 30px;
    margin-left: 30px;
}
.btn-groupy{
    margin-top: 5px;
    margin-bottom: 70px;
    margin-left: auto; 
    margin-right: 20;
    right: -50px;
   
    
}
.contar{
    margin-left: 30px;
}


/*.pagination {
  display: inline-block;
}*/

.pagination li a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;
  margin: 0 4px;
}

.pagination li a.active {
  background-color: #4CAF50;
  color: white;
  border: 1px solid #4CAF50;
}
.cent{
    align-items: center !important;
}
.pagination li a:hover:not(.active) {background-color: #ddd;}


/* Responsive layout - makes a one column layout instead of a two-column layout */
@media (max-width: 800px) {
  .flex-item-right, .flex-item-left {
    flex: 100%;
  }
}
    </style>
   
  

<!--pagination-->
   {% load pagination_tags %}

<div class="search-section">
   
    <h1 class="search-result">available Properties</h1>

    <!--listing all properties-->
   {% for result in propertyItems %} 
<div class="flex-container">
  <div>
    <div class="property-flex">
        
        <a href="{% url 'product:image_gallery' result.id %}">
        <div class="card-image ">
            <img src="{{ result.img.url }}" alt="">
        </div>
        </a>
    </div>
  </div>
  <div>
      <div class="property-information">
         <a href="{% url 'product:image_gallery' result.id %}">
            <div class="property-address">
                <h2>{{result.Location }}</h2>
            </div>
         </a>
          <div class="property-information">
              <h3>Price:<span>₦{{result.price }}</span></h3>
              <h3>bedroom:{{result.bedroom }}</h3>
              <h3>bathroom:{{result.bathroom }}</h3>
              <h3>Sqft:{{result.sqft }}</h3>
              <h3>Acres:{{result.acre}}</h3>
              <h3>SubdivisionSee Legal Description Below.</h3>
             
          </div>
      </div>
  </div>
  <div class="property-information">
      <h3 class="right">{{ result.listing_id }}</h3>
  </div>  
  <div class="property-information">
    <h3 class="center">{{ result.release_date }}</h3>

    
</div>  
</div>
<pre class="description"> {{result.describe }}</pre>
<div class="contar">
<div class="btn-groupy " role="group" aria-label="Basic mixed styles example">
    <a href="{% url 'product:image_gallery' result.id %}" type="button" class="btn btnb btn-danger">View pictures {{number}}</a>
    <a href="{% url 'product:image_slides' result.id %}" type="button" class="btn btnb btn-warning">Visual Tour</a>
  
    <a href="{% url 'product:add_item' result.id %}" type="button" class="btn btnb btn-success" >Add To Your Wishlist</a>
    <a href="{% url 'product:image_gallery' result.id %}" type="button" class="btn btnb btn-dark">View Details</a>
  </div>
</div>
{% endfor %}
</div>

<!--pagination pages-->
  
  {% if propertyItems.has_other_pages %}
    <ul class="pagination cent" >
      {% if propertyItems.has_previous %}
        <li><a href="?page={{ propertyItems.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for item in propertyItems.paginator.page_range %}
        {% if propertyItems.number == item %}
          <li class="active"><span>{{ item }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ item }}">{{ item }}</a></li>
        {% endif %}
      {% endfor %}
      {% if propertyItems.has_next %}
        <li><a href="?page={{ propertyItems.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}



{% include 'footer.html' %}
{% endblock %}

templates/email.html
{% extends 'first.html' %}
 {% load static %}
 
 {% block title %}Email Confirmation{% endblock %}
{% block content %}


<style>
     .want_to_buy{
        display: none;
    }
    .display{
        display: none;
    }
    .property-search{
        display: none;
    }
    .featured{
        display: none;
    }

    .email-received{
        margin-bottom: 120px;
        margin-top: 100px;
        font-size: 18px;
        text-align: center;
        color: #cf2e2e;
    }
    .email-received p{
        text-align: center;
        font-size: 14px;
        color: #333;
    }
  
  </style>
<center class="email-received">
    <h1> Thank you , {{ message_name }}</h1>
    <p>Email recieved,we will contact you soon</p>
</center>



{% include 'footer.html' %}
{% endblock %}

templates/footer.html
<style>
    .footer-dark {
        margin-top: 50px;
  padding:50px 0;
  color:#f0f9ff;
  background-color:#282d32;
  width: 100% !important;
}

.footer-dark h3 {
  margin-top:0;
  margin-bottom:12px;
  font-weight:bold;
  font-size:16px;
}

.footer-dark ul {
  padding:0;
  list-style:none;
  line-height:1.6;
  font-size:14px;
  margin-bottom:0;
}

.footer-dark ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.6;
}

.footer-dark ul a:hover {
  opacity:0.8;
}


@media (max-width:767px) {
  .footer-dark .item:not(.social) {
    text-align:center;
    padding-bottom:20px;
  }
}

.footer-dark .item.text {
  margin-bottom:36px;
}

@media (max-width:767px) {
  .footer-dark .item.text {
    margin-bottom:0;
  }
}

.footer-dark .item.text p {
  opacity:0.6;
  margin-bottom:0;
}

.footer-dark .item.social {
  text-align:center;
}

@media (max-width:991px) {
  .footer-dark .item.social {
    text-align:center;
    margin-top:20px;
  }
}

.footer-dark .item.social > a {
  font-size:20px;
  width:36px;
  height:36px;
  line-height:36px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  box-shadow:0 0 0 1px rgba(255,255,255,0.4);
  margin:0 8px;
  color:#fff;
  opacity:0.75;
}

.footer-dark .item.social > a:hover {
  opacity:0.9;
}

.footer-dark .copyright {
  text-align:center;
  padding-top:24px;

  font-size:13px;
  margin-bottom:0;
  color: #fff;
}
</style>







  
 
   
<!--footer information-->

<body>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Address</h3>
                        <ul><li><a href="" style="font-size: 20px">Wilmot Innovation Limited</a></li>
                            <li><a href="#">New Kubwa Village,</a></li>
                            <li><a href="#">Abuja</a></li>
                           
                        </ul>
                    </div>
                    
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#"> Estate Management </a></li>
                            <li><a href="#">Property Sales</a></li>
                            <li><a href="#">Leasing</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Agency</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Phone</h3>
                        <ul>
                        
                            <li><a href="#">+2347044110261</a></li>
                            <li><a href="#" style="color: #fff;font-size:16px;">You can contact us on whatsapp with the above number</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Email</h3>
                        <ul>
                            <li><a href="https://accounts.google.com/ServiceLogin/identifier?continue=https%3A%2F%2Fmyaccount.google.com%3Futm_source%3Daccount-marketing-page%26utm_medium%3Dcreate-account-button&flowName=GlifWebSignIn&flowEntry=ServiceLogin">contact@wilmotinnovation.com</a></li>
                            <li><a href="#"></a></li>
                          
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Office Hours</h3>
                        <ul>
                            <li><a href="#"> Mon – Fri | 9:00 – 5:00pm</a></li>
                            <li><a href="#">Sat – Sun | By Appointment</a></li>
                            <li><a href="#">Holidays -</a></li>
                        </ul>
                    </div>
                  
                    <div class="col-sm-6 col-md-3 item" style="margin-top: 30px;">
                        <h3>About Us</h3>
                        <ul>
                            <li><a href="{% url 'product:home' %}">Home</a></li>
                            <li><a href="{% url 'product:our_team' %}">Our Team</a></li>
                        
                            <li> <a href="{% url 'product:property' %}">Property Search</a> </li>
                            <li class="services"><a href="{% url 'product:services' %}">Our Services</a></li>
                            <li><a href="{% url 'product:management' %}">Property  Management</a></li>
                            <li><a href="{% url 'product:marketing' %}">Marketing</a></li>
                            <li><a href="{% url 'product:testimonial' %}">Testimonials</a></li>
                            
                            <li><a href="{% url 'product:contactus' %}">Contact Us</a></li>
                        </ul>
                    </div>
                   
                    



                    <div class="col item social">
                        <a href="https://m.facebook.com/wilmotinnovationlimited/"><i class="icon ion-social-facebook"></i></a>
                        <a href="#"><i class="icon ion-social-twitter"></i></a>
                        <a href="#"><i class="icon ion-social-snapchat"></i></a>
                        <a href="#"><i class="icon ion-social-instagram"></i></a>
                    </div>
                </div>
                <p class="copyright">Wilmot Estate  © 2022</p>
            </div>
           
        </footer>
        <p class="copyright" style="text-align:left; margin-left:3px" >Devloped by: nuel4xelence@gmail.com</p>
    </div>
    
   

templates/home.html
{% extends 'first.html' %}
{% load static %}


{% block title %}Wilmot innovation homePage{% endblock %}
{% block content %}



<!--sidebar fixed icons-->
<div class="icon-bar">
 
    <a href="https://m.facebook.com/wilmotinnovationlimited/" class="facebook"><i class="fab fa-facebook"></i></a>
    <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
    <a href="#" class="google"><i class="fab fa-google-plus-square"></i></a>
    <a href="#" class="instagram"><i class="fab fa-instagram"></i></a>
    <a href="#" class="youtube"><i class="fab fa-youtube"></i></a>
    <a href="#" class="linkedin"><i class="fab fa-linkedin"></i></a>
   
  </div> 


  <!---display image and texts-->
<section class="want_to_buy" id="want_buy">
    <div class="container">
     <div class="row justify-content-center">
      
             <div class="col">
                 <div class="text">
            
                     <div class="buy animate__animated animate__backInLeft animation-delay-2s" style="animation-delay: 2s;">
                         <h3>looking to buy or sell a home?</h3>
                         <h3>Are you looking for a house to rent?</h3>

                         <h1><strong>Let our local experts work for you.</strong></h1>
                         <h3>The Federal Capital Is Our Office</h3>

                     </div>
                     <div class="local animate__animated animate__backInLeft animation-delay-s" style="animation-delay: 1s;">
                     </div>

                 </div>
             </div>
         
     </div>

    </div>
</section>

{% if user.is_superuser %}
<p>visitors:{{count}}</p>
{% endif  %}

   
 

   
   
   
<section class="display">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="text-head">

                <h1 style="text-align: center;"><span style="color: #000000;">Welcome TO</span></h1>
                <h1 style="text-align: center;"><span style="color: #000000;">Wilmot Innovation Limited</span></h1>
                <h1 style="text-align: center;"><span style="color: #000000;">Real Estate Agency</span></h1>
                </div>
      
<!--<p>&nbsp;</p>-->
<p style="text-align: center;">Our elite real estate professionals work throughout Federal Capital Territory to bring smiles to your face as your real estate professionals.</p>

<p style="text-align: center;">When you’re ready to buy or sell your home, farm, ranch, land or commercial property, let our team help. We are a locally owned and operated company, and we’re ready to help make the buying and selling process much easier. We are the best in the area due to our extensive knowledge, experience and dedication to our clients.</p>


<p style="text-align: center;">Our real estate professionals handle the transactions of many property types such as residential homes, ranches and farms, land and commercial real estate. We do it all. Choosing an expert real estate team, like Wilmot Innovation Real Estate, is the obvious choice to make your buying or selling process seamless. Securing the Company and its team of negotiators will protect you from mistakes and pay dividends in peace of mind and cash.</p>



<p style="text-align: center;">We are in the business of making our clients’ dreams a reality, and our dedication to that is relentless. Having the right agent at your side makes a huge difference, but choosing one of our extremely knowledgeable agents makes ALL the difference.  Call us today and let us get started!.</p>
<h2 style="text-align: center;"><span class="wilmotBasin" style="color: #000000;">The Wilmot Innovation  real estate professionals  are the right agents for your housing projects</span></h2>
            </div>

    <div class="col-md-6">

        <div class="video-wrap">
            <div class="video">
                <div class="video__thumbn">
                    <video width="480" height="300" controls>
                        <source src="/static/video/wilmot_innovation1.MP4" type=video/mp4></video>
                </div>
            </div>
        </div>
        <div class="wrap-inner">
            <img class="img-with-animation skip-lazy animated-in" data-delay="0" height="450" width="450" data-animation="fade-in" src="{% static 'images/pic/wilmot.jpg' %}" alt="">
          </div>

			</div> 
		</div>
	</div> 
</section>



<!--property selection-->

<div class=" property-search" style="align-items: center; text-align: center;">
    <div class="form-container" >
        <h2>Search for any property below:</h2>
     <form id="make_checkbox_select" method="POST" action="{% url 'product:property_search' %}">
         {% csrf_token %}
         <h4>property type</h4>
         <select name="property" class="property">
             <option  data-count="2" value="all" >All</option>
             <option data-count="23" value="Residential">Residential</option>
             <option data-count="433" value="Commercial">Commercial</option>
             <option data-count="45" value="Land">Land</option>
             <option data-count="476" value="Multi_family">Multi-Family</option>
             <option data-count="78" value="Rental">Rental</option>
           
         </select>
         
         <div class="flex">
         <div class="form-content" style=" align-items: center; text-align: center;">
            <div class="row g-3 align-items-center" style="text-align: left; align-items: right;">
                 <div class="col-auto">
                   <label for="text" class="col-form-label">Min Price</label>
                   <input type="number" id="inputPassword6" class="form-control inputinfo" aria-describedby="passwordHelpInline" name="min-price" placeholder="ex 200000">
                 
                 </div>
                 <div class="col-auto">
                     <label for="text" class="col-form-label">Max Price</label>
                     <input type="number" id="inputPassword6" class="form-control inputinfo" aria-describedby="passwordHelpInline" name="max-price" placeholder="ex 500000">
                   
                   </div>
               </div>
 
 
               <div class="row g-4 align-items-center" style="text-align: left; align-items: right;">
                 <div class="col-auto">
                   <label for="text" class="col-form-label">Min Bedrooms</label>
                   <input type="number" id="inputPassword6" class="form-control inputinfo" aria-describedby="passwordHelpInline" name="bedroom" placeholder="ex 1">
                 
                 </div>
                 <div class="col-auto">
                     <label for="text" class="col-form-label">Min Baths</label>
                     <input type="number" id="inputPassword6" class="form-control inputinfo" aria-describedby="passwordHelpInline" name="bathroom" placeholder="ex 2">
                   
                   </div>
               </div>
             
            </div>
            
            
        </div>
        <button class="btn btn-outline-success" id="btn-select" type="submit">Search</button>
       </form>
     
    </div>
               
         </div>


          
          
 
  <!--feature listing-->


<section class="featured" id="featured">
    <div class="container">
        <h2 class="listing">FEATURED LISTINGS</h2>
        <div class="row owl-carousel owl-theme">
            {% for property in rented %}
            <div class="col">
               <a href="{% url 'product:feature_gallery' property.id %}">
                <div class="card">
                    <div class="card-img">
                        <img src="{{ property.img.url }}" alt="">
                    </div>
                    <div class="card-body">
                        <p> {{property.street_name}}<br> {{property.location }}</p>
                        <span> ₦{{property.price}}</span>
                   
                    </div>
                </div>
               </a>
            </div>
           {% endfor %}
           
        </div>
    </div>   
</section>



<script>
  $(document).ready(function(){
    if ($('.owl-carousel').length){
    $('.owl-carousel').owlCarousel({
        loop:true,
        //margin:10,
        nav:true,

       // autoplayTimeout: 2000,
        autoplay:true,
   
        responsiveClass:true,
        responsive:{
            0:{
                card:1,
                
            },
         
            600:{
                card:2,
               
            },
            900:{
                card:4,

            },
            1000:{
                card:4,
               
                loop:true,
            }
        }
    })
}
})

</script>

{% include 'footer.html' %}

{% endblock %}

templates/property_info.html
{% extends 'first.html' %}
{% load static %}
{% block title %}PropertyInformation{% endblock %}
{% block content %}



<style>

    .want_to_buy{
        display: none;
    }
    .display{
        display: none;
    }
    .property-search{
        display: none;
    }
    .featured{
        display: none;
    }


.flex-container {
  display: flex;
  flex-wrap: wrap;
  margin-top: 25px;
}

.flex-item-left {
  flex: 50%;
}

.flex-item-right {
  flex: 50%;
}
.card-image{
    width: 300px;
    height: 280px;
    margin-left: 20px;
}
.card-image img{
    width: 100%;
    height: 100%;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    border: 2px solid #7bdcb5;
}
.property-information{
    margin-left: 20px;
}
.property-address h2{
    font-size: 20px;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    font-weight: 400;
  
    color: #0076AD;
    margin-left: 10px;
}
.property-information h3{
    font-size: 18px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #333;

}
.property-information span{
    color: green;
}
.right{
    margin-left: 50px;
}
.search-result{
    margin-left: 30px;
}
.search-section .description{
    font-size: 15px;
    color: #333;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    margin-top: 30px;
    margin-left: 30px;
}
.btn-groupy{
    margin-top: 5px;
    margin-bottom: 70px;
    margin-left: auto; 
    margin-right: 20;
    right: -50px;
   
    
}
.contar{
    margin-left: 30px;
}

/* Responsive layout - makes a one column layout instead of a two-column layout */
@media (max-width: 800px) {
  .flex-item-right, .flex-item-left {
    flex: 100%;
  }
}
    </style>
   
  
<!--pagination-->

   {% load pagination_tags %}

<div class="search-section">
    {% if result %}
    <h3 class="search-result">{{ result }}</h3>
    {% elif noProperty %}
    <h1 class="search-result">{{noProperty}}</h1>
      {% else %}  
    <h1 class="search-result">Search result</h1>
    {% endif %}
    


    <!--property information-->
   {% for result in resultobj %} 
<div class="flex-container">
    
   
  <div>
  
    <div class="property-flex">
        
        <a href="{% url 'product:image_gallery' result.id %}">
        <div class="card-image ">
            <img src="{{ result.img.url }}" alt="">
        </div>
        </a>
    </div>
  </div>
  <div>
      <div class="property-information">
         <a href="{% url 'product:image_gallery' result.id %}">
            <div class="property-address">
                <h2>{{result.Location }}</h2>
            </div>
         </a>
          <div class="property-information">
              <h3>Price:<span>₦{{result.price }}</span></h3>
              <h3>bedroom:{{result.bedroom }}</h3>
              <h3>bathroom:{{result.bathroom }}</h3>
              <h3>Sqft:{{result.sqft }}</h3>
              <h3>Acres:{{result.acre}}</h3>
              <h3>SubdivisionSee Legal Description Below.</h3>
             
          </div>
      </div>
  </div>
  <div class="property-information">
      <h3 class="right">{{ result.listing_id }}</h3>
    
  </div>  
  <div class="property-information">
    <h3 class="center">{{ result.release_date }}</h3>
    
</div>  
</div>
<pre class="description"> {{result.describe }}</pre>
<div class="contar">
<div class="btn-groupy " role="group" aria-label="Basic mixed styles example">
    <a href="{% url 'product:image_gallery' result.id %}" type="button" class="btn btnb btn-danger">View pictures {{number}}</a>
    <a href="{% url 'product:image_slides' result.id %}" type="button" class="btn btnb btn-warning">Visual Tour</a>
  
    <a href="{% url 'product:add_item' result.id %}" type="button" class="btn btnb btn-success" >Add To Your Wishlist</a>
    <a href="{% url 'product:image_gallery' result.id %}" type="button" class="btn btnb btn-dark">View Details</a>
  </div>
</div>
{% endfor %}
</div>







{% include 'footer.html' %}
{% endblock %}

templates/search_result.html
{% extends 'first.html' %}
{% load static %}
{% block title %}SearchResult{% endblock%}
{% block content %}



<style>

   
.my-5 p,h5{
 font-size: 18px;
 font-family: Arial, Helvetica, sans-serif;
 font-weight: 200;
 
}

.flex-container {
  display: flex;
  flex-wrap: wrap;
  margin-top: 25px;
}

.flex-item-left {
  flex: 50%;
}

.flex-item-right {
  flex: 50%;
}

.property-information{
    margin-left: 20px;
}
.property-address h2{
    font-size: 20px;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    font-weight: 400;
  
    color: #0076AD;
    margin-left: 10px;
}
.property-information h3{
    font-size: 18px;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #333;

}
.property-information span{
    color: green;
}
.right{
    margin-left: 50px;
}
.search-result{
    margin-left: 30px;
}
.search-section .description{
    font-size: 15px;
    color: #333;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    margin-top: 30px;
    margin-left: 30px;
}
.btn-groupy{
    margin-top: 5px;
    margin-bottom: 70px;
    margin-left: auto; 
    margin-right: 20;
    right: -50px;
   
    
}
.contar{
    margin-left: 30px;
}
.prod .col-md-4{
    box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.2) !important;
    

}
/* Responsive layout - makes a one column layout instead of a two-column layout */
@media (max-width: 800px) {
  .flex-item-right, .flex-item-left {
    flex: 100%;
  }
}
    </style>
   
  
<!--pagination-->
   {% load pagination_tags %}
  

<div class="prod">
    <div class="container">
        {% if result %}
        <h3 class="search-result">{{ result }}</h3>
        {% else %}
        <h1 class="search-result">Search result</h1>
        {% endif %}
       
        <!--display properties avaialble -->
        <div class="row my-5">
            {% for result in resultobj %}
            
            <div class="col-md-4 my-4  animate__animated animate__backInLeft animation-delay-s" style="animation-delay: 1s;">
                <a href="{% url 'product:image_gallery' result.id %}">
                <h4 class="my-" style="font-size: 18px; color: #0076AD;"><span style=" color: #000; text-decoration: none; font-size: 20px;">Location:</span>{{result.Location }}</h4></a>
                <img  src="{{ result.img.url }}" alt="" class="w-100" style="width: 250px; height: 180px;">
                <h5 class="card-title">Price:<span style="color: green;">₦{{result.price }}</span></h5>
                
                <h5>bedroom:{{result.bedroom }} &nbsp;bedroom:{{result.bathroom}}</h5>
 
                <h5>Sqft:{{result.sqft }} &nbsp;Acres:{{result.acre}}</h5>
                <p>{{ result.release_date }}</p>
          
                       <ul>
                        <a href="{% url 'product:image_gallery' result.id %}" type="button" class="btn btnb btn-danger">View pictures</a>
                        <a href="{% url 'product:image_slides' result.id %}" type="button" class="btn btnb btn-warning">Visual Tour</a>
                      
                       </ul>
                      <ul>
                        <a href="{% url 'product:add_item' result.id %}" type="button" class="btn btnb btn-success" >Add To Wishlist</a>
                        <a href="{% url 'product:image_gallery' result.id %}" type="button" class="btn btnb btn-dark">View Details</a>
                    
                      </ul>
            </div>
            {% endfor %}
  
        </div>
    </div>
    </div>




    {% include 'footer.html' %}    
{% endblock %}

templates/status.html
<br>

<!--orderr status -->
<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.get_total_count }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Services Completed</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title"> Pending Services </h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{pending}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>